// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProTherm.Models;

namespace ProTherm.Migrations
{
    [DbContext(typeof(ProThermDbContext))]
    partial class ProThermDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProTherm.Models.Mutant", b =>
                {
                    b.Property<long>("mutantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PDB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ddg")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("mutation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pdburl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("site")
                        .HasColumnType("int");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.HasKey("mutantID");

                    b.ToTable("Mutants");
                });
#pragma warning restore 612, 618
        }
    }
}
